/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp.n1.nicolas.mozo.classes;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mozo
 */
public class BeerProducter implements Runnable{
    // Attributes
    private final BeerHouse tBeerHouse;
    private final int iProductorID;
    private final int WAITINGTIME = 1500;
    /**
     * BeerProducter's Constructor
     * @param ptBeerHouse
     * @param idProductor 
     */
    public BeerProducter(BeerHouse ptBeerHouse, int idProductor) {
        this.tBeerHouse = ptBeerHouse;
        this.iProductorID = idProductor;
    }   
    /**
     * Override the run method that implements from the Runnable's Interface
     */
    @Override
    public void run() {
        // Unlimited time man! It's Free!
        while(true){
            // Try to make something magic
            try {
                // Put a beer
                System.out.println("El productor agrego una birrita.");
                // Wait a second please..
                Thread.sleep(WAITINGTIME);
            // If some erros ocurrs (I don't belive it, because this code is amazing and programmed by me)
            } catch (InterruptedException ex) {
                // Make something cool that is auto-generated by the NetBeans
                // Yeah, I'm using this IDE because IntelliJ is a piece of shit.
                Logger.getLogger(BeerProducter.class.getName()).log(Level.SEVERE, null, ex);
            }
        }       
    }
    
    
}
